CREATE TABLE quads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sideA DOUBLE NOT NULL,
    sideB DOUBLE NOT NULL,
    sideC DOUBLE NOT NULL,
    sideD DOUBLE NOT NULL,
    type VARCHAR(50) NOT NULL
);